# Generated by Django 4.0.4 on 2022-06-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_marca_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('region', models.TextField(choices=[[0, 'Seleccione Region'], [1, 'region 1'], [2, 'region 2'], [3, 'region 3'], [4, 'region 4']])),
                ('avisos', models.BooleanField()),
            ],
        ),
    ]
