# Generated by Django 4.0.4 on 2022-06-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='region',
            field=models.IntegerField(choices=[[0, 'Seleccione Region'], [1, 'region 1'], [2, 'region 2'], [3, 'region 3'], [4, 'region 4']]),
        ),
    ]
