# Generated by Django 4.0.4 on 2022-06-02 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_contacto_region'),
        ('core', '0006_rename_nombre_contacto_name_alter_contacto_region'),
    ]

    operations = [
    ]
