# Generated by Django 4.0.4 on 2022-06-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20220601_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
