# Generated by Django 4.0.4 on 2022-06-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20220601_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='name',
            new_name='nombre',
        ),
    ]
