# Generated by Django 4.0.4 on 2022-06-07 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_producto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='marca',
            new_name='categoria',
        ),
    ]
